name: Build server to gh-pages

on: [push, pull_request]

jobs:
  deploy-server:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Generate
        run: yarn run generate

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

#      - name: Run SSH command to update at server
#        uses: garygrossgarten/github-action-ssh@v0.6.3
#        with:
#          command: sh ~/update_code.sh
#          host: ${{ secrets.HOST_X }}
#          username: ${{ secrets.USERNAME_X }}
#          password: ${{ secrets.PASSWORD_X }}

